### ISSUE TITLE
docker compose error

### ISSUE THREAD

**Issue by lycettk** [oriavsapir/Command-And-Control-PHP#2]
can you help please! I get error trying when run docker compose up -d all seems to run perfect then...

failed to solve: process "/bin/sh -C apt update -y && docker-php-ext-install mysqli php-cli php-json php-mbstring php-xml php-pcov php-xdebug" did not complete successfully: exit code 1.

appreciate any ideas. thanks

**Comment by lycettk** [comment]
fixed thanks

**Comment by oriavsapir** [comment]
Hi,
Idk what happened . but you right.

I was removing the packages "php-cli php-json php-mbstring php-xml php-pcov php-xdebug" from the Dockerfile to resolve the issue.

If you encounter any further issues or have any other questions, feel free to reach out. I'm here to help. Additionally, if there are any other improvements or changes you'd like to explore, please let me know, and I'll be happy to assist you further.

Thank you for bringing this issue to my attention, and I'm glad I could help you resolve it.
